
package ru.otus.rik.web.jaxws.salary.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RikSalaryService", targetNamespace = "http://service.salary.jaxws.web.rik.otus.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RikSalaryService {


    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "averageSalary", targetNamespace = "http://service.salary.jaxws.web.rik.otus.ru/", className = "ru.otus.rik.web.jaxws.salary.client.AverageSalary")
    @ResponseWrapper(localName = "averageSalaryResponse", targetNamespace = "http://service.salary.jaxws.web.rik.otus.ru/", className = "ru.otus.rik.web.jaxws.salary.client.AverageSalaryResponse")
    @Action(input = "http://service.salary.jaxws.web.rik.otus.ru/RikSalaryService/averageSalaryRequest", output = "http://service.salary.jaxws.web.rik.otus.ru/RikSalaryService/averageSalaryResponse")
    public double averageSalary();

}
