
package ru.otus.rik.web.jaxws.fee.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FeeWebService", targetNamespace = "http://service.fee.jaxws.web.rik.otus.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FeeWebService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateFeeForProfit", targetNamespace = "http://service.fee.jaxws.web.rik.otus.ru/", className = "ru.otus.rik.web.jaxws.fee.client.CalculateFeeForProfit")
    @ResponseWrapper(localName = "calculateFeeForProfitResponse", targetNamespace = "http://service.fee.jaxws.web.rik.otus.ru/", className = "ru.otus.rik.web.jaxws.fee.client.CalculateFeeForProfitResponse")
    @Action(input = "http://service.fee.jaxws.web.rik.otus.ru/FeeWebService/calculateFeeForProfitRequest", output = "http://service.fee.jaxws.web.rik.otus.ru/FeeWebService/calculateFeeForProfitResponse")
    public double calculateFeeForProfit(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
